### ISSUE TITLE
bigtable: emulator 'unexpected fault address'

### ISSUE THREAD

**Issue by pkriete** [GoogleCloudPlatform/google-cloud-go#410]
I'm seeing some very regular failures of the bigtable emulator. After just a handful of requests it bails out with an 'unexpected fault address'.

Any ideas? Not a go programmer, but happy to help debug where possible.

```
[bigtable] Cloud Bigtable emulator running on 127.0.0.1:8721
[bigtable] unexpected fault address 0xb01dfacedebac1e
[bigtable] fatal error: fault
[bigtable] [signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x5b72a]
[bigtable] 
[bigtable] goroutine 560 [running]:
[bigtable] runtime.throw(0x604200, 0x5)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/runtime/panic.go:547 +0x90 fp=0xc82013ba10 sp=0xc82013b9f8
[bigtable] runtime.sigpanic()
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/runtime/sigpanic_unix.go:27 +0x2ba fp=0xc82013ba60 sp=0xc82013ba10
[bigtable] runtime.memeqbody()
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/runtime/asm_amd64.s:1378 +0x8a fp=0xc82013ba68 sp=0xc82013ba60
[bigtable] runtime.mapaccess1_faststr(0x43ad20, 0xc8201569c0, 0x10c89cacdb29a, 0x12, 0x375d7c89)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/runtime/hashmap_fast.go:219 +0x125 fp=0xc82013bac8 sp=0xc82013ba68
[bigtable] golang.org/x/net/trace.(*trace).Finish(0xc8201e6600)
[bigtable]  /usr/local/google/home/garyelliott/go/src/golang.org/x/net/trace/trace.go:375 +0x1c4 fp=0xc82013bbf8 sp=0xc82013bac8
[bigtable] google.golang.org/grpc.(*Server).processStreamingRPC.func1(0xc8201c82d0, 0xc82013be18)
[bigtable]  /usr/local/google/home/garyelliott/go/src/google.golang.org/grpc/server.go:682 +0xc4 fp=0xc82013bc78 sp=0xc82013bbf8
[bigtable] google.golang.org/grpc.(*Server).processStreamingRPC(0xc82019a6e0, 0xc36670, 0xc8201c8900, 0xc8203224b0, 0xc8201c0d80, 0x912c80, 0xc8203859e0, 0x0, 0x0)
[bigtable]  /usr/local/google/home/garyelliott/go/src/google.golang.org/grpc/server.go:720 +0x6ee fp=0xc82013bde0 sp=0xc82013bc78
[bigtable] google.golang.org/grpc.(*Server).handleStream(0xc82019a6e0, 0xc36670, 0xc8201c8900, 0xc8203224b0, 0xc8203859e0)
[bigtable]  /usr/local/google/home/garyelliott/go/src/google.golang.org/grpc/server.go:773 +0x1151 fp=0xc82013bf38 sp=0xc82013bde0
[bigtable] google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc82014d8c0, 0xc82019a6e0, 0xc36670, 0xc8201c8900, 0xc8203224b0)
[bigtable]  /usr/local/google/home/garyelliott/go/src/google.golang.org/grpc/server.go:422 +0xa0 fp=0xc82013bf68 sp=0xc82013bf38
[bigtable] runtime.goexit()
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82013bf70 sp=0xc82013bf68
[bigtable] created by google.golang.org/grpc.(*Server).serveStreams.func1
[bigtable]  /usr/local/google/home/garyelliott/go/src/google.golang.org/grpc/server.go:423 +0x9a
[bigtable] 
[bigtable] goroutine 1 [select (no cases)]:
[bigtable] main.main()
[bigtable]  /usr/local/google/home/garyelliott/go/src/cloud.google.com/go/bigtable/cmd/emulator/cbtemulator.go:41 +0x387
[bigtable] 
[bigtable] goroutine 33 [IO wait]:
[bigtable] net.runtime_pollWait(0xc36190, 0x72, 0xa90028)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/runtime/netpoll.go:160 +0x60
[bigtable] net.(*pollDesc).Wait(0xc8201c6290, 0x72, 0x0, 0x0)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/net/fd_poll_runtime.go:73 +0x3a
[bigtable] net.(*pollDesc).WaitRead(0xc8201c6290, 0x0, 0x0)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/net/fd_poll_runtime.go:78 +0x36
[bigtable] net.(*netFD).accept(0xc8201c6230, 0x0, 0xc36520, 0xc8201939a0)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/net/fd_unix.go:426 +0x27c
[bigtable] net.(*TCPListener).AcceptTCP(0xc82014e110, 0xc82004ef00, 0x0, 0x0)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/net/tcpsock_posix.go:254 +0x4d
[bigtable] net.(*TCPListener).Accept(0xc82014e110, 0x0, 0x0, 0x0, 0x0)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/net/tcpsock_posix.go:264 +0x3d
[bigtable] google.golang.org/grpc.(*Server).Serve(0xc82019a6e0, 0xc36360, 0xc82014e110, 0x0, 0x0)
[bigtable]  /usr/local/google/home/garyelliott/go/src/google.golang.org/grpc/server.go:348 +0x1cf
[bigtable] created by cloud.google.com/go/bigtable/bttest.NewServer
[bigtable]  /usr/local/google/home/garyelliott/go/src/cloud.google.com/go/bigtable/bttest/inmem.go:97 +0x322
[bigtable] 
[bigtable] goroutine 44 [select]:
[bigtable] google.golang.org/grpc/transport.(*http2Server).controller(0xc8201c8900)
[bigtable]  /usr/local/google/home/garyelliott/go/src/google.golang.org/grpc/transport/http2_server.go:673 +0x6ed
[bigtable] created by google.golang.org/grpc/transport.newHTTP2Server
[bigtable]  /usr/local/google/home/garyelliott/go/src/google.golang.org/grpc/transport/http2_server.go:139 +0x8fa
[bigtable] 
[bigtable] goroutine 43 [IO wait]:
[bigtable] net.runtime_pollWait(0xc360d0, 0x72, 0xc82020c000)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/runtime/netpoll.go:160 +0x60
[bigtable] net.(*pollDesc).Wait(0xc8201c6d80, 0x72, 0x0, 0x0)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/net/fd_poll_runtime.go:73 +0x3a
[bigtable] net.(*pollDesc).WaitRead(0xc8201c6d80, 0x0, 0x0)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/net/fd_poll_runtime.go:78 +0x36
[bigtable] net.(*netFD).Read(0xc8201c6d20, 0xc82020c000, 0x8000, 0x8000, 0x0, 0xa90028, 0xc82006c0a0)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/net/fd_unix.go:250 +0x23a
[bigtable] net.(*conn).Read(0xc82014e1c8, 0xc82020c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/net/net.go:172 +0xe4
[bigtable] bufio.(*Reader).fill(0xc82019ede0)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/bufio/bufio.go:97 +0x1e9
[bigtable] bufio.(*Reader).Read(0xc82019ede0, 0xc8201e63f8, 0x9, 0x9, 0x7ff7, 0x0, 0x0)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/bufio/bufio.go:207 +0x260
[bigtable] io.ReadAtLeast(0xc365f8, 0xc82019ede0, 0xc8201e63f8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/io/io.go:297 +0xe6
[bigtable] io.ReadFull(0xc365f8, 0xc82019ede0, 0xc8201e63f8, 0x9, 0x9, 0x131c227122c76001, 0x0, 0x0)
[bigtable]  /usr/local/google/home/garyelliott/dl_go/go/src/io/io.go:315 +0x62
[bigtable] golang.org/x/net/http2.readFrameHeader(0xc8201e63f8, 0x9, 0x9, 0xc365f8, 0xc82019ede0, 0x0, 0xc800000000, 0x0, 0x0)
[bigtable]  /usr/local/google/home/garyelliott/go/src/golang.org/x/net/http2/frame.go:237 +0xa5
[bigtable] golang.org/x/net/http2.(*Framer).ReadFrame(0xc8201e63c0, 0x0, 0x0, 0x0, 0x0)
[bigtable]  /usr/local/google/home/garyelliott/go/src/golang.org/x/net/http2/frame.go:464 +0x106
[bigtable] google.golang.org/grpc/transport.(*framer).readFrame(0xc820208240, 0x0, 0x0, 0x0, 0x0)
[bigtable]  /usr/local/google/home/garyelliott/go/src/google.golang.org/grpc/transport/http_util.go:508 +0x3d
[bigtable] google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc8201c8900, 0xc8202082d0)
[bigtable]  /usr/local/google/home/garyelliott/go/src/google.golang.org/grpc/transport/http2_server.go:260 +0x6fa
[bigtable] google.golang.org/grpc.(*Server).serveStreams(0xc82019a6e0, 0xc36670, 0xc8201c8900)
[bigtable]  /usr/local/google/home/garyelliott/go/src/google.golang.org/grpc/server.go:424 +0x159
[bigtable] google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc82019a6e0, 0xc36548, 0xc82014e1c8, 0x0, 0x0)
[bigtable]  /usr/local/google/home/garyelliott/go/src/google.golang.org/grpc/server.go:411 +0x49d
[bigtable] google.golang.org/grpc.(*Server).handleRawConn(0xc82019a6e0, 0xc36548, 0xc82014e1c8)
[bigtable]  /usr/local/google/home/garyelliott/go/src/google.golang.org/grpc/server.go:388 +0x53d
[bigtable] created by google.golang.org/grpc.(*Server).Serve
[bigtable]  /usr/local/google/home/garyelliott/go/src/google.golang.org/grpc/server.go:357 +0x38c
[bigtable] 
[bigtable] goroutine 41 [select]:
[bigtable] cloud.google.com/go/bigtable/bttest.(*server).gcloop(0xc820153440, 0xc82019e900)
[bigtable]  /usr/local/google/home/garyelliott/go/src/cloud.google.com/go/bigtable/bttest/inmem.go:751 +0x2ff
[bigtable] created by cloud.google.com/go/bigtable/bttest.(*server).needGC
[bigtable]  /usr/local/google/home/garyelliott/go/src/cloud.google.com/go/bigtable/bttest/inmem.go:737 +0x9c
```

**Comment by garye** [comment]
Interesting, it looks like the error is happening in the grpc tracing stuff. We can try a build that doesn't have tracing turned on. Would you be able to pull down the go client and run a local copy of the emulator? I can walk you through what needs to happen to disable tracing but it involves a code change.

**Comment by pkriete** [comment]
Sure thing!

Just grabbed all the bits and bobs and it seems to be working. In fact using `go run cbtemulator.go` it hasn't crashed yet. Should I be doing anything to simulate the build process? Build flags or anything of the sort?

**Comment by garye** [comment]
Great, thanks! I should have also asked what platform you're on. This has had the most testing on linux.

Here's how I build the emulator:

`env GOOS=$1 GOARCH=$2 go build cbtemulator.go`

Where $1 and $2 are specific to your platform, but the options are:

`darwin 386`
`darwin amd64`
`linux 386`
`linux amd64`

Hopefully (?) you can reproduce the problem. If so give this fix a try to see if it helps:
https://code-review.googlesource.com/#/c/9091/

Let me know how it goes!

**Comment by pkriete** [comment]
It's OS X 10.12. No luck reproducing on the locally built version. I tried going back a few commits as well, still nothing.

I suppose my issue is fixed, I don't mind running from source.

Definitely let me know if you want me to try anything else though! Otherwise I'll just try the gcloud binary again when that patch goes live.

**Comment by zavale** [comment]
Hi @garye, I am facing exactly the same problem.
I am also not a Go programmer. Could you please post detail instructions how to build https://code-review.googlesource.com/#/c/9091/ locally? I am working on MacOS 10.12.1.
Thanks!

**Comment by garye** [comment]
Can you possibly try this binary to see if it fixes your problem? [bigtable_darwin_amd64.tar.gz](https://github.com/GoogleCloudPlatform/google-cloud-go/files/581839/bigtable_darwin_amd64.tar.gz)

**Comment by zavale** [comment]
@garye
I tried, and looks more stable, but still crashes - please see the log below:
`Cloud Bigtable emulator running on 127.0.0.1:8020
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x55264940bca pc=0xf25b]

runtime stack:
runtime.throw(0x6d27a0, 0x2a)
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x92bb40)
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x92bb40, 0x1, 0xe, 0xc820001840)
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7fff5fbff878)
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x92bb40, 0x1, 0x1000000000e, 0xeeff)
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x92d430, 0x0)
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x92d430, 0xc8201e6130)
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0xa0d000, 0xe, 0x0)
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0x926400)
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/proc.go:1051

goroutine 67 [running]:
runtime.systemstack_switch()
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/asm_amd64.s:245 fp=0xc8200696d0 sp=0xc8200696c8
runtime.mallocgc(0xd0, 0x56a000, 0x0, 0xc82002c6e8)
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/malloc.go:643 +0x869 fp=0xc8200697a8 sp=0xc8200696d0
runtime.newarray(0x56a000, 0x1, 0xc7b0ee9e04eb4460)
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/malloc.go:798 +0xc9 fp=0xc8200697e8 sp=0xc8200697a8
runtime.mapassign1(0x440320, 0xc8201f7d10, 0xc8200698e8, 0xc8200698d0)
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/hashmap.go:453 +0x134 fp=0xc820069890 sp=0xc8200697e8
cloud.google.com/go/bigtable/bttest.toColumnFamilies(0xc8201f7ce0, 0xc8201f7ce0)
	/tmp/go/src/cloud.google.com/go/bigtable/bttest/inmem.go:1035 +0x13f fp=0xc820069960 sp=0xc820069890
cloud.google.com/go/bigtable/bttest.(*server).GetTable(0xc820143200, 0xa62cd0, 0xc8201f7bf0, 0xc8201f3180, 0x0, 0x0, 0x0)
	/tmp/go/src/cloud.google.com/go/bigtable/bttest/inmem.go:155 +0x252 fp=0xc820069a30 sp=0xc820069960
google.golang.org/genproto/googleapis/bigtable/admin/v2._BigtableTableAdmin_GetTable_Handler(0x5dcc40, 0xc820143200, 0xa62cd0, 0xc8201f7bf0, 0xc8201f0ff0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/go/src/google.golang.org/genproto/googleapis/bigtable/admin/v2/bigtable_table_admin.pb.go:624 +0x168 fp=0xc820069ad8 sp=0xc820069a30
google.golang.org/grpc.(*Server).processUnaryRPC(0xc8201980c0, 0xa62bc0, 0xc820074090, 0xc820017950, 0xc820160f30, 0x91f1f0, 0x0, 0x0, 0x0)
	/tmp/go/src/google.golang.org/grpc/server.go:638 +0x1098 fp=0xc820069df0 sp=0xc820069ad8
google.golang.org/grpc.(*Server).handleStream(0xc8201980c0, 0xa62bc0, 0xc820074090, 0xc820017950, 0x0)
	/tmp/go/src/google.golang.org/grpc/server.go:796 +0x10a0 fp=0xc820069f48 sp=0xc820069df0
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc820011b50, 0xc8201980c0, 0xa62bc0, 0xc820074090, 0xc820017950)
	/tmp/go/src/google.golang.org/grpc/server.go:449 +0xa0 fp=0xc820069f78 sp=0xc820069f48
runtime.goexit()
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820069f80 sp=0xc820069f78
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/tmp/go/src/google.golang.org/grpc/server.go:450 +0x9a

goroutine 1 [select (no cases)]:
main.main()
	/usr/local/google/home/garyelliott/go/src/cloud.google.com/go/bigtable/cmd/emulator/cbtemulator.go:43 +0x38e

goroutine 33 [IO wait]:
net.runtime_pollWait(0xae7248, 0x72, 0xa5d050)
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201be140, 0x72, 0x0, 0x0)
	/usr/local/google/home/garyelliott/dl_go/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201be140, 0x0, 0x0)
	/usr/local/google/home/garyelliott/dl_go/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201be0e0, 0x0, 0xae75d8, 0xc820119260)
	/usr/local/google/home/garyelliott/dl_go/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc820146130, 0xc820048e20, 0x0, 0x0)
	/usr/local/google/home/garyelliott/dl_go/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820146130, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/garyelliott/dl_go/go/src/net/tcpsock_posix.go:264 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc8201980c0, 0xae73a0, 0xc820146130, 0x0, 0x0)
	/tmp/go/src/google.golang.org/grpc/server.go:354 +0x1e4
created by cloud.google.com/go/bigtable/bttest.NewServer
	/tmp/go/src/cloud.google.com/go/bigtable/bttest/inmem.go:97 +0x322

goroutine 34 [select]:
cloud.google.com/go/bigtable/bttest.(*server).gcloop(0xc820143200, 0xc820196360)
	/tmp/go/src/cloud.google.com/go/bigtable/bttest/inmem.go:800 +0x2ff
created by cloud.google.com/go/bigtable/bttest.(*server).needGC
	/tmp/go/src/cloud.google.com/go/bigtable/bttest/inmem.go:786 +0x9c

goroutine 7 [IO wait]:
net.runtime_pollWait(0xae7188, 0x72, 0xc8201c0000)
	/usr/local/google/home/garyelliott/dl_go/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820050140, 0x72, 0x0, 0x0)
	/usr/local/google/home/garyelliott/dl_go/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820050140, 0x0, 0x0)
	/usr/local/google/home/garyelliott/dl_go/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200500e0, 0xc8201c0000, 0x8000, 0x8000, 0x0, 0xa5d050, 0xc820010048)
	/usr/local/google/home/garyelliott/dl_go/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002c1a8, 0xc8201c0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/google/home/garyelliott/dl_go/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc82006e3c0)
	/usr/local/google/home/garyelliott/dl_go/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc82006e3c0, 0xc82011e0f8, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/google/home/garyelliott/dl_go/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0xa62b48, 0xc82006e3c0, 0xc82011e0f8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/google/home/garyelliott/dl_go/go/src/io/io.go:297 +0xe6
io.ReadFull(0xa62b48, 0xc82006e3c0, 0xc82011e0f8, 0x9, 0x9, 0xc820001380, 0x0, 0x0)
	/usr/local/google/home/garyelliott/dl_go/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc82011e0f8, 0x9, 0x9, 0xa62b48, 0xc82006e3c0, 0xff000000, 0x0, 0x0, 0x0)
	/tmp/go/src/golang.org/x/net/http2/frame.go:237 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc82011e0c0, 0x0, 0x0, 0x0, 0x0)
	/tmp/go/src/golang.org/x/net/http2/frame.go:464 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc82015c8a0, 0x0, 0x0, 0x0, 0x0)
	/tmp/go/src/google.golang.org/grpc/transport/http_util.go:508 +0x3d
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc820074090, 0xc82015c930)
	/tmp/go/src/google.golang.org/grpc/transport/http2_server.go:260 +0x6fa
google.golang.org/grpc.(*Server).serveStreams(0xc8201980c0, 0xa62bc0, 0xc820074090)
	/tmp/go/src/google.golang.org/grpc/server.go:451 +0x159
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc8201980c0, 0xa62a98, 0xc82002c1a8, 0x0, 0x0)
	/tmp/go/src/google.golang.org/grpc/server.go:438 +0x49d
google.golang.org/grpc.(*Server).handleRawConn(0xc8201980c0, 0xa62a98, 0xc82002c1a8)
	/tmp/go/src/google.golang.org/grpc/server.go:415 +0x53d
created by google.golang.org/grpc.(*Server).Serve
	/tmp/go/src/google.golang.org/grpc/server.go:384 +0x75c

goroutine 8 [select]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc820074090)
	/tmp/go/src/google.golang.org/grpc/transport/http2_server.go:674 +0x6ed
created by google.golang.org/grpc/transport.newHTTP2Server
	/tmp/go/src/google.golang.org/grpc/transport/http2_server.go:139 +0x8fa`

**Comment by garye** [comment]
I can't reproduce this yet but I'm running 10.11.6. I'll try again after upgrading. Can you provide any details about the workload you're running against the emulator?

Here are some instructions to build locally which seemed to help @pkriete:

- Install Go (https://golang.org/dl)
- Set your `GOPATH` (https://github.com/golang/go/wiki/GOPATH) to some directory.
- Install the google-cloud-go library (https://cloud.google.com/bigtable/docs/go/)
- `cd $GOPATH/src/cloud.google.com/go/bigtable/cmd/emulator`
- `go run cbtemulator.go`

Also take a look above at how to compile a binary instead of using `go run`. Let me know if you have any luck.

**Comment by garye** [comment]
Oh... We need to compile with the newest version of Go to support 10.12: https://golang.org/doc/go1.7#ports

@pkriete, I'll put a build up here when I have one for you to try out (but feel free to try the steps above if you don't want to wait!)

**Comment by zavale** [comment]
Hi @garye 
Right now as a workaround, I am running Ubuntu on VM, on my Mac, and on Ubuntu running Linux version of the emulators(I use also Pubsub). After setting proper NAT Port Forwarding, I am able to configure Local Host settings for Bigtable, when the actual emulators are on VM. Please let me know when I can switch back to the native(Mac) simulators.

Thank you for your help!!!

**Comment by garye** [comment]
I build this version with Go 1.7.3 and tested on a laptop running Sierra. Looks good to me. @zavale, would you be willing to try it out?

https://storage.googleapis.com/cloud-bigtable-emulator/cbtemulator.tar

**Comment by zavale** [comment]
@garye I performed pretty heavy testing on this version - and it's very stable.
Thanks a lot!
Please post a comment here, once the official version released with the fix

**Comment by garye** [comment]
Glad to hear it! Will do.

**Comment by garye** [comment]
Today's gcloud update has a bigtable emulator built with go 1.7.3 and it works on my macOS sierra laptop. 

Give it a shot, and please re-open if the issue resurfaces!
